bundler:
  image: debian:jessie
  volumes:
    - /bundle

web:
  build: .
  ports:
    - "4010:3000"
  volumes:
    - .:/app/
  volumes_from:
    - bundler
  command: bundle exec foreman start web
  #command: bundle exec rails s -p 3000 -b '0.0.0.0'
